import { defineConfig, globalIgnores } from 'eslint/config'
import nextVitals from 'eslint-config-next/core-web-vitals'
import nextTs from 'eslint-config-next/typescript'

/*
 * ESLint 9 flat config, replacing .eslintrc.json.
 *
 * The move was forced rather than chosen: `next lint` was removed in Next 16, and
 * eslint-config-next@16 requires ESLint >= 9, which only reads flat config.
 *
 * eslint-config-next@16 ships NATIVE flat configs, so there is no FlatCompat and
 * no @eslint/eslintrc shim here. `core-web-vitals` is the base plus the Core Web
 * Vitals rules promoted from warning to error; `typescript` adds the
 * typescript-eslint recommended set. Both were previously pulled in by the
 * "next/core-web-vitals" and "next/typescript" strings in .eslintrc.json, so the
 * rule surface is the same.
 *
 * Scope note: this lints the WHOLE repo, including scripts/. `next lint` only
 * covered a handful of directories, so the switch widened coverage and did in
 * fact surface real unused symbols in scripts/ that had never been checked.
 */
const eslintConfig = defineConfig([
  ...nextVitals,
  ...nextTs,
  {
    /*
     * THREE RULES DELIBERATELY DEFERRED, NOT DISMISSED.
     *
     * eslint-plugin-react-hooks v6 (pulled in by eslint-config-next@16) adds the
     * React Compiler era rules. They flag 16 pre-existing sites in this codebase:
     *
     *   react-hooks/set-state-in-effect  11  cascading renders from setState in an effect
     *   react-hooks/purity                4  impure reads during render
     *   react-hooks/refs                  1  ref access during render
     *
     * These are real signals and are worth acting on. They are OFF here because
     * every one of them needs the effect's intent understood before it is moved,
     * across the login page, the header, the arcade game and the visual effects
     * layer. Doing that inside an ESLint version bump would put a fleet of
     * behavioural changes in a commit whose purpose is tooling, where nobody would
     * think to review them and no test covers most of them.
     *
     * The migration's goal was parity with the previous rule surface on a
     * supported ESLint. Adopting a new rule set is separate work; see
     * docs/SECURITY.md for the follow-up note. Re-enable one rule at a time and
     * fix its sites in a change that says so.
     */
    rules: {
      'react-hooks/set-state-in-effect': 'off',
      'react-hooks/purity': 'off',
      'react-hooks/refs': 'off',
    },
  },
  globalIgnores([
    // Defaults that eslint-config-next would otherwise apply on its own. Listing
    // them explicitly is required: supplying globalIgnores replaces them.
    '.next/**',
    'out/**',
    'build/**',
    'next-env.d.ts',
    // Project specific, carried over verbatim from .eslintrc.json.
    // Migrations are generated by Payload and are not hand edited.
    'src/migrations/**',
    // Generated by `payload generate:importmap`.
    'src/app/(payload)/admin/importMap.js',
  ]),
])

export default eslintConfig
