/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    clubs: Club;
    'certification-types': CertificationType;
    certifications: Certification;
    'certificate-files': CertificateFile;
    courses: Course;
    pathways: Pathway;
    'consent-records': ConsentRecord;
    'incident-log': IncidentLog;
    pages: Page;
    announcements: Announcement;
    media: Media;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    clubs: ClubsSelect<false> | ClubsSelect<true>;
    'certification-types': CertificationTypesSelect<false> | CertificationTypesSelect<true>;
    certifications: CertificationsSelect<false> | CertificationsSelect<true>;
    'certificate-files': CertificateFilesSelect<false> | CertificateFilesSelect<true>;
    courses: CoursesSelect<false> | CoursesSelect<true>;
    pathways: PathwaysSelect<false> | PathwaysSelect<true>;
    'consent-records': ConsentRecordsSelect<false> | ConsentRecordsSelect<true>;
    'incident-log': IncidentLogSelect<false> | IncidentLogSelect<true>;
    pages: PagesSelect<false> | PagesSelect<true>;
    announcements: AnnouncementsSelect<false> | AnnouncementsSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {
    'policy-versions': PolicyVersion;
    'site-settings': SiteSetting;
    'header-nav': HeaderNav;
    'footer-nav': FooterNav;
  };
  globalsSelect: {
    'policy-versions': PolicyVersionsSelect<false> | PolicyVersionsSelect<true>;
    'site-settings': SiteSettingsSelect<false> | SiteSettingsSelect<true>;
    'header-nav': HeaderNavSelect<false> | HeaderNavSelect<true>;
    'footer-nav': FooterNavSelect<false> | FooterNavSelect<true>;
  };
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  fullName: string;
  preferredName?: string | null;
  pronouns?: string | null;
  phone?: string | null;
  /**
   * Determines whether the participant is a minor (under 18). Minors are guardian-managed.
   */
  dateOfBirth: string;
  /**
   * Derived from date of birth on every save.
   */
  isMinor?: boolean | null;
  profilePhoto?: (number | null) | Media;
  bio?: string | null;
  club?: (number | null) | Club;
  /**
   * Role assignment is restricted to super admins.
   */
  roles: ('participant' | 'coach' | 'official' | 'club_admin' | 'super_admin')[];
  /**
   * Pending = awaiting guardian confirmation (minors). System/admin set.
   */
  status: 'active' | 'pending' | 'inactive';
  /**
   * When set, this account is exempt from erasure (legal/safety hold).
   */
  legalHold?: boolean | null;
  emergencyContact?: {
    name?: string | null;
    relationship?: string | null;
    phone?: string | null;
  };
  /**
   * Recorded at signup and on re-consent. Audited in ConsentRecords.
   */
  consents?: {
    termsVersion?: string | null;
    privacyVersion?: string | null;
    guardianConsentVersion?: string | null;
    acceptedAt?: string | null;
    acceptedIp?: string | null;
    marketingOptIn?: boolean | null;
    photoOptIn?: boolean | null;
  };
  /**
   * Required for participants under 18. The account stays pending until confirmed.
   */
  guardian?: {
    name?: string | null;
    email?: string | null;
    phone?: string | null;
    relationship?: string | null;
    confirmed?: boolean | null;
    confirmationToken?: string | null;
  };
  notificationPrefs?: {
    certificationReminders?: boolean | null;
    generalUpdates?: boolean | null;
  };
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  /**
   * Alt text for accessibility. Describe the image.
   */
  alt: string;
  caption?: string | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
  sizes?: {
    thumbnail?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    card?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    hero?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "clubs".
 */
export interface Club {
  id: number;
  name: string;
  shortName?: string | null;
  logo?: (number | null) | Media;
  contactEmail?: string | null;
  contactPhone?: string | null;
  /**
   * Users who administer this club.
   */
  admins?: (number | User)[] | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "certification-types".
 */
export interface CertificationType {
  id: number;
  name: string;
  category: 'coach' | 'official' | 'compliance' | 'medical';
  /**
   * Roles this certification is relevant to.
   */
  appliesToRoles?: ('participant' | 'coach' | 'official' | 'club_admin' | 'super_admin')[] | null;
  /**
   * Months a certification of this type stays valid. Blank = does not expire. Used to auto-compute expiry.
   */
  validityMonths?: number | null;
  /**
   * Is this certification mandatory for its required roles?
   */
  isRequired?: boolean | null;
  /**
   * Roles for which this certification is mandatory.
   */
  requiredForRoles?: ('participant' | 'coach' | 'official' | 'club_admin' | 'super_admin')[] | null;
  /**
   * Deep-link to renew / take the course.
   */
  renewalUrl?: string | null;
  /**
   * Course that fulfills this certification, if any.
   */
  relatedCourse?: (number | null) | Course;
  description?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "courses".
 */
export interface Course {
  id: number;
  title: string;
  description?: string | null;
  /**
   * e.g. Reach360 (CMBA), Coaching Association of Canada, RAMP.
   */
  provider?: string | null;
  /**
   * e.g. Online, self-paced; In-person clinic.
   */
  format?: string | null;
  level?: string | null;
  cost?: string | null;
  duration?: string | null;
  targetAudience?: string | null;
  registerUrl?: string | null;
  mandatory?: boolean | null;
  requiredForRoles?: ('participant' | 'coach' | 'official' | 'club_admin' | 'super_admin')[] | null;
  relatedCertificationType?: (number | null) | CertificationType;
  /**
   * Provider course id (e.g. Reach360 course UUID), for sync/dedupe.
   */
  externalId?: string | null;
  modules?:
    | {
        number?: number | null;
        title: string;
        description?: string | null;
        id?: string | null;
      }[]
    | null;
  tags?:
    | {
        tag: string;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "certifications".
 */
export interface Certification {
  id: number;
  user: number | User;
  type: number | CertificationType;
  /**
   * Auto-computed from verification + expiry.
   */
  status?: ('pending-verification' | 'valid' | 'expiring' | 'expired') | null;
  issueDate?: string | null;
  /**
   * Auto-filled from the type validity if left blank.
   */
  expiryDate?: string | null;
  /**
   * Private file (owner + admin only). Never public.
   */
  certificateFile?: (number | null) | CertificateFile;
  issuingBody?: string | null;
  credentialId?: string | null;
  /**
   * Admin who verified this certification. Admin-only.
   */
  verifiedBy?: (number | null) | User;
  /**
   * Set when an admin verifies. Admin-only.
   */
  verifiedAt?: string | null;
  notes?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Private certificate files. Downloads are access-controlled; never public.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "certificate-files".
 */
export interface CertificateFile {
  id: number;
  /**
   * The user this certificate file belongs to.
   */
  owner: number | User;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pathways".
 */
export interface Pathway {
  id: number;
  name: string;
  audience: 'coach' | 'official';
  description?: string | null;
  stages: {
    name: string;
    description?: string | null;
    /**
     * Sort order (1 = first stage).
     */
    order: number;
    /**
     * XP awarded for completing this stage.
     */
    xpReward?: number | null;
    /**
     * Certifications a user must hold (valid) to complete this stage.
     */
    requiredCertificationTypes?: (number | CertificationType)[] | null;
    id?: string | null;
  }[];
  updatedAt: string;
  createdAt: string;
}
/**
 * Immutable consent audit log.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "consent-records".
 */
export interface ConsentRecord {
  id: number;
  user: number | User;
  kind: 'initial' | 'reconsent';
  isMinor?: boolean | null;
  termsVersion?: string | null;
  privacyVersion?: string | null;
  guardianConsentVersion?: string | null;
  marketingOptIn?: boolean | null;
  photoOptIn?: boolean | null;
  acceptedAt: string;
  acceptedIp?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Privacy/security incident & breach log (PIPEDA accountability).
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "incident-log".
 */
export interface IncidentLog {
  id: number;
  title: string;
  severity: 'low' | 'medium' | 'high' | 'critical';
  status: 'open' | 'investigating' | 'contained' | 'closed';
  occurredAt: string;
  discoveredAt?: string | null;
  /**
   * If true, OPC + affected individuals must be notified (PIPEDA).
   */
  realRiskOfSignificantHarm?: boolean | null;
  /**
   * Office of the Privacy Commissioner notification date.
   */
  opcNotifiedAt?: string | null;
  individualsNotifiedAt?: string | null;
  affectedCount?: number | null;
  description?: string | null;
  remediation?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages".
 */
export interface Page {
  id: number;
  title: string;
  /**
   * URL path, e.g. "about" → /about. Use "home" for the homepage slot.
   */
  slug: string;
  layout?: (HeroBlock | RichTextBlock | StatsGridBlock | FAQBlock | CTABlock | ImageBlock | EmbedBlock)[] | null;
  seo?: {
    metaTitle?: string | null;
    metaDescription?: string | null;
    ogImage?: (number | null) | Media;
  };
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "HeroBlock".
 */
export interface HeroBlock {
  eyebrow?: string | null;
  heading: string;
  subheading?: string | null;
  ctaLabel?: string | null;
  ctaHref?: string | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'hero';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "RichTextBlock".
 */
export interface RichTextBlock {
  content: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  id?: string | null;
  blockName?: string | null;
  blockType: 'richText';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "StatsGridBlock".
 */
export interface StatsGridBlock {
  stats?:
    | {
        value: string;
        label: string;
        id?: string | null;
      }[]
    | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'statsGrid';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "FAQBlock".
 */
export interface FAQBlock {
  heading?: string | null;
  items?:
    | {
        question: string;
        answer: string;
        id?: string | null;
      }[]
    | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'faq';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "CTABlock".
 */
export interface CTABlock {
  heading: string;
  body?: string | null;
  buttonLabel: string;
  buttonHref: string;
  id?: string | null;
  blockName?: string | null;
  blockType: 'cta';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ImageBlock".
 */
export interface ImageBlock {
  image: number | Media;
  caption?: string | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'image';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "EmbedBlock".
 */
export interface EmbedBlock {
  title?: string | null;
  /**
   * URL to embed in an iframe (e.g. a TeamLinkt schedule).
   */
  url: string;
  height?: number | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'embed';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "announcements".
 */
export interface Announcement {
  id: number;
  title: string;
  body?: string | null;
  /**
   * e.g. Registration, Schedule, Safety.
   */
  tag?: string | null;
  /**
   * Optional URL the announcement links to.
   */
  link?: string | null;
  pinned?: boolean | null;
  publishedAt?: string | null;
  /**
   * Hidden from the site after this date.
   */
  expiresAt?: string | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'clubs';
        value: number | Club;
      } | null)
    | ({
        relationTo: 'certification-types';
        value: number | CertificationType;
      } | null)
    | ({
        relationTo: 'certifications';
        value: number | Certification;
      } | null)
    | ({
        relationTo: 'certificate-files';
        value: number | CertificateFile;
      } | null)
    | ({
        relationTo: 'courses';
        value: number | Course;
      } | null)
    | ({
        relationTo: 'pathways';
        value: number | Pathway;
      } | null)
    | ({
        relationTo: 'consent-records';
        value: number | ConsentRecord;
      } | null)
    | ({
        relationTo: 'incident-log';
        value: number | IncidentLog;
      } | null)
    | ({
        relationTo: 'pages';
        value: number | Page;
      } | null)
    | ({
        relationTo: 'announcements';
        value: number | Announcement;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  fullName?: T;
  preferredName?: T;
  pronouns?: T;
  phone?: T;
  dateOfBirth?: T;
  isMinor?: T;
  profilePhoto?: T;
  bio?: T;
  club?: T;
  roles?: T;
  status?: T;
  legalHold?: T;
  emergencyContact?:
    | T
    | {
        name?: T;
        relationship?: T;
        phone?: T;
      };
  consents?:
    | T
    | {
        termsVersion?: T;
        privacyVersion?: T;
        guardianConsentVersion?: T;
        acceptedAt?: T;
        acceptedIp?: T;
        marketingOptIn?: T;
        photoOptIn?: T;
      };
  guardian?:
    | T
    | {
        name?: T;
        email?: T;
        phone?: T;
        relationship?: T;
        confirmed?: T;
        confirmationToken?: T;
      };
  notificationPrefs?:
    | T
    | {
        certificationReminders?: T;
        generalUpdates?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "clubs_select".
 */
export interface ClubsSelect<T extends boolean = true> {
  name?: T;
  shortName?: T;
  logo?: T;
  contactEmail?: T;
  contactPhone?: T;
  admins?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "certification-types_select".
 */
export interface CertificationTypesSelect<T extends boolean = true> {
  name?: T;
  category?: T;
  appliesToRoles?: T;
  validityMonths?: T;
  isRequired?: T;
  requiredForRoles?: T;
  renewalUrl?: T;
  relatedCourse?: T;
  description?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "certifications_select".
 */
export interface CertificationsSelect<T extends boolean = true> {
  user?: T;
  type?: T;
  status?: T;
  issueDate?: T;
  expiryDate?: T;
  certificateFile?: T;
  issuingBody?: T;
  credentialId?: T;
  verifiedBy?: T;
  verifiedAt?: T;
  notes?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "certificate-files_select".
 */
export interface CertificateFilesSelect<T extends boolean = true> {
  owner?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "courses_select".
 */
export interface CoursesSelect<T extends boolean = true> {
  title?: T;
  description?: T;
  provider?: T;
  format?: T;
  level?: T;
  cost?: T;
  duration?: T;
  targetAudience?: T;
  registerUrl?: T;
  mandatory?: T;
  requiredForRoles?: T;
  relatedCertificationType?: T;
  externalId?: T;
  modules?:
    | T
    | {
        number?: T;
        title?: T;
        description?: T;
        id?: T;
      };
  tags?:
    | T
    | {
        tag?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pathways_select".
 */
export interface PathwaysSelect<T extends boolean = true> {
  name?: T;
  audience?: T;
  description?: T;
  stages?:
    | T
    | {
        name?: T;
        description?: T;
        order?: T;
        xpReward?: T;
        requiredCertificationTypes?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "consent-records_select".
 */
export interface ConsentRecordsSelect<T extends boolean = true> {
  user?: T;
  kind?: T;
  isMinor?: T;
  termsVersion?: T;
  privacyVersion?: T;
  guardianConsentVersion?: T;
  marketingOptIn?: T;
  photoOptIn?: T;
  acceptedAt?: T;
  acceptedIp?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "incident-log_select".
 */
export interface IncidentLogSelect<T extends boolean = true> {
  title?: T;
  severity?: T;
  status?: T;
  occurredAt?: T;
  discoveredAt?: T;
  realRiskOfSignificantHarm?: T;
  opcNotifiedAt?: T;
  individualsNotifiedAt?: T;
  affectedCount?: T;
  description?: T;
  remediation?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages_select".
 */
export interface PagesSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  layout?:
    | T
    | {
        hero?: T | HeroBlockSelect<T>;
        richText?: T | RichTextBlockSelect<T>;
        statsGrid?: T | StatsGridBlockSelect<T>;
        faq?: T | FAQBlockSelect<T>;
        cta?: T | CTABlockSelect<T>;
        image?: T | ImageBlockSelect<T>;
        embed?: T | EmbedBlockSelect<T>;
      };
  seo?:
    | T
    | {
        metaTitle?: T;
        metaDescription?: T;
        ogImage?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "HeroBlock_select".
 */
export interface HeroBlockSelect<T extends boolean = true> {
  eyebrow?: T;
  heading?: T;
  subheading?: T;
  ctaLabel?: T;
  ctaHref?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "RichTextBlock_select".
 */
export interface RichTextBlockSelect<T extends boolean = true> {
  content?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "StatsGridBlock_select".
 */
export interface StatsGridBlockSelect<T extends boolean = true> {
  stats?:
    | T
    | {
        value?: T;
        label?: T;
        id?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "FAQBlock_select".
 */
export interface FAQBlockSelect<T extends boolean = true> {
  heading?: T;
  items?:
    | T
    | {
        question?: T;
        answer?: T;
        id?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "CTABlock_select".
 */
export interface CTABlockSelect<T extends boolean = true> {
  heading?: T;
  body?: T;
  buttonLabel?: T;
  buttonHref?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ImageBlock_select".
 */
export interface ImageBlockSelect<T extends boolean = true> {
  image?: T;
  caption?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "EmbedBlock_select".
 */
export interface EmbedBlockSelect<T extends boolean = true> {
  title?: T;
  url?: T;
  height?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "announcements_select".
 */
export interface AnnouncementsSelect<T extends boolean = true> {
  title?: T;
  body?: T;
  tag?: T;
  link?: T;
  pinned?: T;
  publishedAt?: T;
  expiresAt?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  caption?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
  sizes?:
    | T
    | {
        thumbnail?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        card?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        hero?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "policy-versions".
 */
export interface PolicyVersion {
  id: number;
  /**
   * Current Terms of Use version (e.g. a date or semver).
   */
  termsVersion: string;
  privacyVersion: string;
  /**
   * Current Guardian Consent & Children’s Privacy Notice version.
   */
  guardianConsentVersion: string;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings".
 */
export interface SiteSetting {
  id: number;
  privacyOfficer?: {
    name?: string | null;
    email?: string | null;
    phone?: string | null;
  };
  contact?: {
    email?: string | null;
    phone?: string | null;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "header-nav".
 */
export interface HeaderNav {
  id: number;
  items?:
    | {
        label: string;
        href: string;
        children?:
          | {
              label: string;
              href: string;
              id?: string | null;
            }[]
          | null;
        id?: string | null;
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "footer-nav".
 */
export interface FooterNav {
  id: number;
  sections?:
    | {
        title: string;
        links?:
          | {
              label: string;
              href: string;
              id?: string | null;
            }[]
          | null;
        id?: string | null;
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "policy-versions_select".
 */
export interface PolicyVersionsSelect<T extends boolean = true> {
  termsVersion?: T;
  privacyVersion?: T;
  guardianConsentVersion?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings_select".
 */
export interface SiteSettingsSelect<T extends boolean = true> {
  privacyOfficer?:
    | T
    | {
        name?: T;
        email?: T;
        phone?: T;
      };
  contact?:
    | T
    | {
        email?: T;
        phone?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "header-nav_select".
 */
export interface HeaderNavSelect<T extends boolean = true> {
  items?:
    | T
    | {
        label?: T;
        href?: T;
        children?:
          | T
          | {
              label?: T;
              href?: T;
              id?: T;
            };
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "footer-nav_select".
 */
export interface FooterNavSelect<T extends boolean = true> {
  sections?:
    | T
    | {
        title?: T;
        links?:
          | T
          | {
              label?: T;
              href?: T;
              id?: T;
            };
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}