/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    clubs: Club;
    'certification-types': CertificationType;
    certifications: Certification;
    'certificate-files': CertificateFile;
    courses: Course;
    pathways: Pathway;
    'consent-records': ConsentRecord;
    'incident-log': IncidentLog;
    'game-reports': GameReport;
    pages: Page;
    announcements: Announcement;
    media: Media;
    seasons: Season;
    divisions: Division;
    teams: Team;
    venues: Venue;
    courts: Court;
    'team-memberships': TeamMembership;
    games: Game;
    'score-reports': ScoreReport;
    'scoresheet-files': ScoresheetFile;
    confirmations: Confirmation;
    disputes: Dispute;
    officials: Official;
    'game-officials': GameOfficial;
    'playoff-brackets': PlayoffBracket;
    'bracket-series': BracketSery;
    'standings-cache': StandingsCache;
    'import-batches': ImportBatch;
    sanctions: Sanction;
    availability: Availability;
    'player-stats': PlayerStat;
    'audit-log': AuditLog;
    'game-incidents': GameIncident;
    'incident-files': IncidentFile;
    'idempotency-keys': IdempotencyKey;
    'refresh-tokens': RefreshToken;
    'rate-limit-hits': RateLimitHit;
    'webauthn-credentials': WebauthnCredential;
    'webauthn-challenges': WebauthnChallenge;
    'mfa-totp': MfaTotp;
    'recovery-codes': RecoveryCode;
    'email-otp': EmailOtp;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    clubs: ClubsSelect<false> | ClubsSelect<true>;
    'certification-types': CertificationTypesSelect<false> | CertificationTypesSelect<true>;
    certifications: CertificationsSelect<false> | CertificationsSelect<true>;
    'certificate-files': CertificateFilesSelect<false> | CertificateFilesSelect<true>;
    courses: CoursesSelect<false> | CoursesSelect<true>;
    pathways: PathwaysSelect<false> | PathwaysSelect<true>;
    'consent-records': ConsentRecordsSelect<false> | ConsentRecordsSelect<true>;
    'incident-log': IncidentLogSelect<false> | IncidentLogSelect<true>;
    'game-reports': GameReportsSelect<false> | GameReportsSelect<true>;
    pages: PagesSelect<false> | PagesSelect<true>;
    announcements: AnnouncementsSelect<false> | AnnouncementsSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    seasons: SeasonsSelect<false> | SeasonsSelect<true>;
    divisions: DivisionsSelect<false> | DivisionsSelect<true>;
    teams: TeamsSelect<false> | TeamsSelect<true>;
    venues: VenuesSelect<false> | VenuesSelect<true>;
    courts: CourtsSelect<false> | CourtsSelect<true>;
    'team-memberships': TeamMembershipsSelect<false> | TeamMembershipsSelect<true>;
    games: GamesSelect<false> | GamesSelect<true>;
    'score-reports': ScoreReportsSelect<false> | ScoreReportsSelect<true>;
    'scoresheet-files': ScoresheetFilesSelect<false> | ScoresheetFilesSelect<true>;
    confirmations: ConfirmationsSelect<false> | ConfirmationsSelect<true>;
    disputes: DisputesSelect<false> | DisputesSelect<true>;
    officials: OfficialsSelect<false> | OfficialsSelect<true>;
    'game-officials': GameOfficialsSelect<false> | GameOfficialsSelect<true>;
    'playoff-brackets': PlayoffBracketsSelect<false> | PlayoffBracketsSelect<true>;
    'bracket-series': BracketSeriesSelect<false> | BracketSeriesSelect<true>;
    'standings-cache': StandingsCacheSelect<false> | StandingsCacheSelect<true>;
    'import-batches': ImportBatchesSelect<false> | ImportBatchesSelect<true>;
    sanctions: SanctionsSelect<false> | SanctionsSelect<true>;
    availability: AvailabilitySelect<false> | AvailabilitySelect<true>;
    'player-stats': PlayerStatsSelect<false> | PlayerStatsSelect<true>;
    'audit-log': AuditLogSelect<false> | AuditLogSelect<true>;
    'game-incidents': GameIncidentsSelect<false> | GameIncidentsSelect<true>;
    'incident-files': IncidentFilesSelect<false> | IncidentFilesSelect<true>;
    'idempotency-keys': IdempotencyKeysSelect<false> | IdempotencyKeysSelect<true>;
    'refresh-tokens': RefreshTokensSelect<false> | RefreshTokensSelect<true>;
    'rate-limit-hits': RateLimitHitsSelect<false> | RateLimitHitsSelect<true>;
    'webauthn-credentials': WebauthnCredentialsSelect<false> | WebauthnCredentialsSelect<true>;
    'webauthn-challenges': WebauthnChallengesSelect<false> | WebauthnChallengesSelect<true>;
    'mfa-totp': MfaTotpSelect<false> | MfaTotpSelect<true>;
    'recovery-codes': RecoveryCodesSelect<false> | RecoveryCodesSelect<true>;
    'email-otp': EmailOtpSelect<false> | EmailOtpSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {
    'policy-versions': PolicyVersion;
    'site-settings': SiteSetting;
    'header-nav': HeaderNav;
    'footer-nav': FooterNav;
  };
  globalsSelect: {
    'policy-versions': PolicyVersionsSelect<false> | PolicyVersionsSelect<true>;
    'site-settings': SiteSettingsSelect<false> | SiteSettingsSelect<true>;
    'header-nav': HeaderNavSelect<false> | HeaderNavSelect<true>;
    'footer-nav': FooterNavSelect<false> | FooterNavSelect<true>;
  };
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  fullName: string;
  preferredName?: string | null;
  pronouns?: string | null;
  phone?: string | null;
  /**
   * Determines whether the participant is a minor (under 18). Minors are guardian-managed.
   */
  dateOfBirth: string;
  /**
   * Derived from date of birth on every save.
   */
  isMinor?: boolean | null;
  profilePhoto?: (number | null) | Media;
  bio?: string | null;
  club?: (number | null) | Club;
  /**
   * Role assignment is restricted to super admins.
   */
  roles: ('participant' | 'coach' | 'official' | 'club_admin' | 'super_admin')[];
  /**
   * Pending = awaiting guardian confirmation (minors). System/admin set.
   */
  status: 'active' | 'pending' | 'inactive';
  /**
   * When set, this account is exempt from erasure (legal/safety hold).
   */
  legalHold?: boolean | null;
  emergencyContact?: {
    name?: string | null;
    relationship?: string | null;
    phone?: string | null;
  };
  /**
   * Recorded at signup and on re-consent. Audited in ConsentRecords.
   */
  consents?: {
    termsVersion?: string | null;
    privacyVersion?: string | null;
    guardianConsentVersion?: string | null;
    acceptedAt?: string | null;
    acceptedIp?: string | null;
    marketingOptIn?: boolean | null;
    photoOptIn?: boolean | null;
  };
  /**
   * Required for participants under 18. The account stays pending until confirmed.
   */
  guardian?: {
    name?: string | null;
    email?: string | null;
    phone?: string | null;
    relationship?: string | null;
    confirmed?: boolean | null;
    confirmationToken?: string | null;
  };
  notificationPrefs?: {
    certificationReminders?: boolean | null;
    generalUpdates?: boolean | null;
    /**
     * Reminders to report or confirm a game score. Transactional escalations are always sent.
     */
    gameReminders?: boolean | null;
  };
  /**
   * MFA state. Secrets live in separate private collections. System-managed.
   */
  mfa?: {
    enrolled?: boolean | null;
    methods?: ('totp' | 'passkey')[] | null;
    enrolledAt?: string | null;
    required?: boolean | null;
    lastVerifiedAt?: string | null;
  };
  sessionMeta?:
    | {
        sid: string;
        aal?: ('aal1' | 'aal2') | null;
        mfaAt?: string | null;
        stepUpAt?: string | null;
        ip?: string | null;
        userAgent?: string | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Registered device push tokens for the native apps. Self-managed.
   */
  pushDevices?:
    | {
        token: string;
        platform?: ('ios' | 'android' | 'web') | null;
        registeredAt?: string | null;
        lastSeenAt?: string | null;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  /**
   * Alt text for accessibility. Describe the image.
   */
  alt: string;
  caption?: string | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
  sizes?: {
    thumbnail?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    card?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    hero?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "clubs".
 */
export interface Club {
  id: number;
  name: string;
  shortName?: string | null;
  logo?: (number | null) | Media;
  contactEmail?: string | null;
  contactPhone?: string | null;
  /**
   * Users who administer this club.
   */
  admins?: (number | User)[] | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "certification-types".
 */
export interface CertificationType {
  id: number;
  name: string;
  category: 'coach' | 'official' | 'compliance' | 'medical';
  /**
   * Roles this certification is relevant to.
   */
  appliesToRoles?: ('participant' | 'coach' | 'official' | 'club_admin' | 'super_admin')[] | null;
  /**
   * Months a certification of this type stays valid. Blank = does not expire. Used to auto-compute expiry.
   */
  validityMonths?: number | null;
  /**
   * Is this certification mandatory for its required roles?
   */
  isRequired?: boolean | null;
  /**
   * Roles for which this certification is mandatory.
   */
  requiredForRoles?: ('participant' | 'coach' | 'official' | 'club_admin' | 'super_admin')[] | null;
  /**
   * Deep-link to renew / take the course.
   */
  renewalUrl?: string | null;
  /**
   * Course that fulfills this certification, if any.
   */
  relatedCourse?: (number | null) | Course;
  description?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "courses".
 */
export interface Course {
  id: number;
  title: string;
  description?: string | null;
  /**
   * e.g. Reach360 (CMBA), Coaching Association of Canada, RAMP.
   */
  provider?: string | null;
  /**
   * e.g. Online, self-paced; In-person clinic.
   */
  format?: string | null;
  level?: string | null;
  cost?: string | null;
  duration?: string | null;
  targetAudience?: string | null;
  registerUrl?: string | null;
  mandatory?: boolean | null;
  requiredForRoles?: ('participant' | 'coach' | 'official' | 'club_admin' | 'super_admin')[] | null;
  relatedCertificationType?: (number | null) | CertificationType;
  /**
   * Provider course id (e.g. Reach360 course UUID), for sync/dedupe.
   */
  externalId?: string | null;
  modules?:
    | {
        number?: number | null;
        title: string;
        description?: string | null;
        id?: string | null;
      }[]
    | null;
  tags?:
    | {
        tag: string;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "certifications".
 */
export interface Certification {
  id: number;
  user: number | User;
  type: number | CertificationType;
  /**
   * Auto-computed from verification + expiry.
   */
  status?: ('pending-verification' | 'valid' | 'expiring' | 'expired') | null;
  issueDate?: string | null;
  /**
   * Auto-filled from the type validity if left blank.
   */
  expiryDate?: string | null;
  /**
   * Private file (owner + admin only). Never public.
   */
  certificateFile?: (number | null) | CertificateFile;
  issuingBody?: string | null;
  credentialId?: string | null;
  /**
   * Admin who verified this certification. Admin-only.
   */
  verifiedBy?: (number | null) | User;
  /**
   * Set when an admin verifies. Admin-only.
   */
  verifiedAt?: string | null;
  notes?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Private certificate files. Downloads are access-controlled; never public.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "certificate-files".
 */
export interface CertificateFile {
  id: number;
  /**
   * The user this certificate file belongs to.
   */
  owner: number | User;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pathways".
 */
export interface Pathway {
  id: number;
  name: string;
  audience: 'coach' | 'official';
  description?: string | null;
  stages: {
    name: string;
    description?: string | null;
    /**
     * Sort order (1 = first stage).
     */
    order: number;
    /**
     * XP awarded for completing this stage.
     */
    xpReward?: number | null;
    /**
     * Certifications a user must hold (valid) to complete this stage.
     */
    requiredCertificationTypes?: (number | CertificationType)[] | null;
    id?: string | null;
  }[];
  updatedAt: string;
  createdAt: string;
}
/**
 * Immutable consent audit log.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "consent-records".
 */
export interface ConsentRecord {
  id: number;
  user: number | User;
  kind: 'initial' | 'reconsent';
  isMinor?: boolean | null;
  termsVersion?: string | null;
  privacyVersion?: string | null;
  guardianConsentVersion?: string | null;
  marketingOptIn?: boolean | null;
  photoOptIn?: boolean | null;
  acceptedAt: string;
  acceptedIp?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Privacy/security incident & breach log (PIPEDA accountability).
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "incident-log".
 */
export interface IncidentLog {
  id: number;
  title: string;
  severity: 'low' | 'medium' | 'high' | 'critical';
  status: 'open' | 'investigating' | 'contained' | 'closed';
  occurredAt: string;
  discoveredAt?: string | null;
  /**
   * If true, OPC + affected individuals must be notified (PIPEDA).
   */
  realRiskOfSignificantHarm?: boolean | null;
  /**
   * Office of the Privacy Commissioner notification date.
   */
  opcNotifiedAt?: string | null;
  individualsNotifiedAt?: string | null;
  affectedCount?: number | null;
  description?: string | null;
  remediation?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Game / incident reports submitted from /game-report.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "game-reports".
 */
export interface GameReport {
  id: number;
  reportType: 'incident' | 'ejection' | 'concern' | 'compliment';
  reporterName: string;
  reporterEmail: string;
  /**
   * Coach, parent, official, etc.
   */
  role?: string | null;
  gameDate?: string | null;
  division?: string | null;
  homeTeam?: string | null;
  awayTeam?: string | null;
  location?: string | null;
  description: string;
  /**
   * Triage status (admin only).
   */
  status?: ('new' | 'reviewing' | 'closed') | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages".
 */
export interface Page {
  id: number;
  title: string;
  /**
   * URL path, e.g. "about" → /about. Use "home" for the homepage slot.
   */
  slug: string;
  layout?: (HeroBlock | RichTextBlock | StatsGridBlock | FAQBlock | CTABlock | ImageBlock | EmbedBlock)[] | null;
  seo?: {
    metaTitle?: string | null;
    metaDescription?: string | null;
    ogImage?: (number | null) | Media;
  };
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "HeroBlock".
 */
export interface HeroBlock {
  eyebrow?: string | null;
  heading: string;
  subheading?: string | null;
  ctaLabel?: string | null;
  ctaHref?: string | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'hero';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "RichTextBlock".
 */
export interface RichTextBlock {
  content: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  id?: string | null;
  blockName?: string | null;
  blockType: 'richText';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "StatsGridBlock".
 */
export interface StatsGridBlock {
  stats?:
    | {
        value: string;
        label: string;
        id?: string | null;
      }[]
    | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'statsGrid';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "FAQBlock".
 */
export interface FAQBlock {
  heading?: string | null;
  items?:
    | {
        question: string;
        answer: string;
        id?: string | null;
      }[]
    | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'faq';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "CTABlock".
 */
export interface CTABlock {
  heading: string;
  body?: string | null;
  buttonLabel: string;
  buttonHref: string;
  id?: string | null;
  blockName?: string | null;
  blockType: 'cta';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ImageBlock".
 */
export interface ImageBlock {
  image: number | Media;
  caption?: string | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'image';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "EmbedBlock".
 */
export interface EmbedBlock {
  title?: string | null;
  /**
   * URL to embed in an iframe (e.g. a TeamLinkt schedule).
   */
  url: string;
  height?: number | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'embed';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "announcements".
 */
export interface Announcement {
  id: number;
  title: string;
  body?: string | null;
  /**
   * e.g. Registration, Schedule, Safety.
   */
  tag?: string | null;
  /**
   * Optional URL the announcement links to.
   */
  link?: string | null;
  pinned?: boolean | null;
  publishedAt?: string | null;
  /**
   * Hidden from the site after this date.
   */
  expiresAt?: string | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * A competition season. Owns standings configuration and the immutable tiebreaker seed.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "seasons".
 */
export interface Season {
  id: number;
  name: string;
  sport?: string | null;
  status: 'setup' | 'active' | 'playoffs' | 'complete' | 'archived';
  startDate: string;
  endDate: string;
  /**
   * League time zone for game times.
   */
  timezone?: string | null;
  defaultGameLengthMinutes?: number | null;
  /**
   * Added to game length for conflict windows.
   */
  bufferMinutes?: number | null;
  /**
   * Stable final standings tiebreaker key. Set once at create, never recomputed.
   */
  seasonSeed?: number | null;
  /**
   * How standings points and tiebreakers are computed. Super admin only.
   */
  standingsConfig?: {
    pointsWin?: number | null;
    pointsLoss?: number | null;
    pointsTie?: number | null;
    /**
     * Applied in order, only among teams still tied. The final tiebreaker is always the season seed.
     */
    tiebreakers?:
      | {
          criterion: 'headToHead' | 'winPct' | 'pointDiff' | 'pointsFor' | 'fewestPointsAgainst' | 'wins';
          id?: string | null;
        }[]
      | null;
    /**
     * Mercy cap. A single game cannot move differential by more than this.
     */
    pointDiffCap?: number | null;
    mercyEnabled?: boolean | null;
    includeForfeits?: boolean | null;
    forfeitScoreFor?: number | null;
    forfeitScoreAgainst?: number | null;
    forfeitWinPoints?: number | null;
    forfeitPenaltyPoints?: number | null;
    /**
     * Whether the points-for tiebreaker uses capped or raw points.
     */
    pointsForBasis?: ('capped' | 'raw') | null;
    /**
     * Plain language explanation of how standings are calculated, shown to families.
     */
    legend?: string | null;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * A division within a season. fullPath is the import match key.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "divisions".
 */
export interface Division {
  id: number;
  /**
   * Exact import match key, for example "Weekend Rec League / U13 Boys / A".
   */
  fullPath: string;
  /**
   * Short label for chips and dropdowns, for example "U13 Boys A".
   */
  displayLabel?: string | null;
  leagueName: string;
  ageGroup: string;
  gender?: ('boys' | 'girls' | 'coed') | null;
  tier?: string | null;
  season: number | Season;
  scheduleType?: ('round_robin_single' | 'round_robin_double' | 'custom') | null;
  /**
   * Officials below this RAMP level get an eligibility warning when assigned.
   */
  requiredRampLevel?: ('none' | 'level1' | 'level2' | 'level3') | null;
  sortOrder?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * A team in a division. Names are unique within a division.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "teams".
 */
export interface Team {
  id: number;
  name: string;
  club?: (number | null) | Club;
  division: number | Division;
  /**
   * Hex value or simple color name.
   */
  color?: string | null;
  logo?: (number | null) | Media;
  /**
   * Prior system id (for example TeamLinkt) kept for migration.
   */
  externalId?: string | null;
  active?: boolean | null;
  importBatch?: (number | null) | ImportBatch;
  updatedAt: string;
  createdAt: string;
}
/**
 * Audit record and undo manifest for a CSV import.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "import-batches".
 */
export interface ImportBatch {
  id: number;
  kind: 'teams' | 'venues' | 'officials' | 'games';
  fileName?: string | null;
  /**
   * Ready / warnings / errors / imported counts.
   */
  counts?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  publishMode?: ('draft' | 'published') | null;
  status: 'pending' | 'committed' | 'undone';
  /**
   * Undo manifest: the collections and ids created by this import.
   */
  createdRecords?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  committedBy?: (number | null) | User;
  committedAt?: string | null;
  undoneBy?: (number | null) | User;
  undoneAt?: string | null;
  undoExpiresAt?: string | null;
  undoWindowMinutes?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * A facility. Courts are modeled separately so conflict checks key on a stable court id.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "venues".
 */
export interface Venue {
  id: number;
  name: string;
  address?: string | null;
  city?: string | null;
  province?: string | null;
  postalCode?: string | null;
  /**
   * Full map link. If blank, the app builds a search link from the address.
   */
  mapsUrl?: string | null;
  /**
   * Parking or entry notes shown to families.
   */
  notes?: string | null;
  /**
   * Dates this venue is unavailable for scheduling.
   */
  blackoutDates?:
    | {
        date: string;
        reason?: string | null;
        id?: string | null;
      }[]
    | null;
  externalId?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * A playing surface at a venue. Court names are unique within a venue.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "courts".
 */
export interface Court {
  id: number;
  name: string;
  venue: number | Venue;
  active?: boolean | null;
  externalId?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Links a user to a team. A verified membership is how a user is allowed to report for a team.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "team-memberships".
 */
export interface TeamMembership {
  id: number;
  user: number | User;
  team: number | Team;
  /**
   * Role on the team. Admin assigned.
   */
  role: 'rep' | 'coach' | 'manager';
  /**
   * A verified membership may report and confirm scores. Admin only.
   */
  verified?: boolean | null;
  /**
   * Admin who verified this membership. Admin only.
   */
  verifiedBy?: (number | null) | User;
  verifiedAt?: string | null;
  /**
   * Email this rep was invited at, for matching on signup.
   */
  invitedEmail?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Scheduled games and results. Transitions go through the games service, not direct edits.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "games".
 */
export interface Game {
  id: number;
  season: number | Season;
  division: number | Division;
  homeTeam: number | Team;
  awayTeam: number | Team;
  venue?: (number | null) | Venue;
  court?: (number | null) | Court;
  /**
   * Stored UTC; entered in the league time zone.
   */
  startAt: string;
  /**
   * Computed from the season game length.
   */
  endAt?: string | null;
  /**
   * Transitions go through the games service. Finalized status is super admin only.
   */
  status: 'scheduled' | 'reported' | 'contested' | 'final' | 'postponed' | 'cancelled' | 'forfeit';
  /**
   * Draft is not visible on the public site.
   */
  publishState: 'draft' | 'published';
  /**
   * Optimistic lock. Bumped on every write.
   */
  version?: number | null;
  homeScore?: number | null;
  awayScore?: number | null;
  periodScores?:
    | {
        period?: number | null;
        home?: number | null;
        away?: number | null;
        id?: string | null;
      }[]
    | null;
  forfeit?: {
    isForfeit?: boolean | null;
    outcome?: ('home_forfeit' | 'away_forfeit' | 'double_forfeit' | 'no_contest') | null;
    forfeitingTeam?: (number | null) | Team;
    reason?: string | null;
  };
  /**
   * Appended by the games service on every change.
   */
  changeLog?:
    | {
        at?: string | null;
        actor?: (number | null) | User;
        actorEmail?: string | null;
        field?: string | null;
        from?: string | null;
        to?: string | null;
        reason?: string | null;
        id?: string | null;
      }[]
    | null;
  /**
   * A bye is not scheduled on a court and never counts in standings.
   */
  isBye?: boolean | null;
  lockedAt?: string | null;
  externalId?: string | null;
  notes?: string | null;
  importBatch?: (number | null) | ImportBatch;
  updatedAt: string;
  createdAt: string;
}
/**
 * Submitted scores. The verified-rep gate is enforced in the beforeChange hook.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "score-reports".
 */
export interface ScoreReport {
  id: number;
  game: number | Game;
  /**
   * The reporting user. Forced to the signed-in user.
   */
  submittedBy: number | User;
  submittedForTeam: number | Team;
  homeScore: number;
  awayScore: number;
  periodScores?:
    | {
        period?: number | null;
        home?: number | null;
        away?: number | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Private photo (the two teams and admins only).
   */
  scoresheetPhoto?: (number | null) | ScoresheetFile;
  notes?: string | null;
  source?: ('web' | 'mobile') | null;
  submittedAt?: string | null;
  idempotencyKey?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Private scoresheet photos. Downloads are access-controlled; never public.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "scoresheet-files".
 */
export interface ScoresheetFile {
  id: number;
  owner: number | User;
  /**
   * The game this scoresheet belongs to. Set at upload and locked.
   */
  game: number | Game;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * Opposing-team confirmations. The four-rule gate is enforced in the beforeChange hook.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "confirmations".
 */
export interface Confirmation {
  id: number;
  game: number | Game;
  scoreReport: number | ScoreReport;
  confirmingUser: number | User;
  confirmingTeam: number | Team;
  decision: 'confirmed' | 'disputed';
  photoAcknowledged?: boolean | null;
  notes?: string | null;
  createdAt: string;
  idempotencyKey?: string | null;
  updatedAt: string;
}
/**
 * Contested-game review requests. Opening one escalates to the scheduling admin.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "disputes".
 */
export interface Dispute {
  id: number;
  game: number | Game;
  raisedBy: number | User;
  reason: string;
  status: 'open' | 'resolved';
  assignedAdminEmail?: string | null;
  resolvedBy?: (number | null) | User;
  resolution?: string | null;
  createdAt: string;
  resolvedAt?: string | null;
  updatedAt: string;
}
/**
 * Referee and official roster.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "officials".
 */
export interface Official {
  id: number;
  name: string;
  email?: string | null;
  phone?: string | null;
  /**
   * RAMP certification level. Used for eligibility warnings.
   */
  rampLevel?: ('level1' | 'level2' | 'level3') | null;
  /**
   * Warn when assigned more games in a day than this.
   */
  maxGamesPerDay?: number | null;
  externalId?: string | null;
  notes?: string | null;
  /**
   * Optional linked account for self-serve availability later.
   */
  linkedUser?: (number | null) | User;
  active?: boolean | null;
  importBatch?: (number | null) | ImportBatch;
  updatedAt: string;
  createdAt: string;
}
/**
 * Official assignments. Each change is audited and emailed.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "game-officials".
 */
export interface GameOfficial {
  id: number;
  game: number | Game;
  official: number | Official;
  /**
   * Denormalized from the official linked account for read scoping.
   */
  officialUserId?: (number | null) | User;
  role: 'referee1' | 'referee2' | 'scorekeeper' | 'other';
  assignedBy?: (number | null) | User;
  assignedAt?: string | null;
  status?: ('assigned' | 'accepted' | 'declined') | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Playoff bracket seeded from a division standings.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "playoff-brackets".
 */
export interface PlayoffBracket {
  id: number;
  name: string;
  division: number | Division;
  season?: (number | null) | Season;
  format: 'single_elim' | 'double_elim';
  status?: ('draft' | 'published' | 'complete') | null;
  /**
   * Ordered team ids frozen at seed time.
   */
  seedSnapshot?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  seededAt?: string | null;
  publishState?: ('draft' | 'published') | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * A matchup in a playoff bracket.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "bracket-series".
 */
export interface BracketSery {
  id: number;
  bracket: number | PlayoffBracket;
  round: number;
  slot: number;
  homeSeed?: number | null;
  awaySeed?: number | null;
  homeTeam?: (number | null) | Team;
  awayTeam?: (number | null) | Team;
  game?: (number | null) | Game;
  feedsInto?: (number | null) | BracketSery;
  feedsIntoSlot?: ('home' | 'away') | null;
  isLosersBracket?: boolean | null;
  winner?: (number | null) | Team;
  updatedAt: string;
  createdAt: string;
}
/**
 * Derived standings cache. Recomputed by the standings service; never edited by hand.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "standings-cache".
 */
export interface StandingsCache {
  id: number;
  division: number | Division;
  /**
   * StandingRow[] in final sorted order, each with a server-assigned rank.
   */
  rows?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  /**
   * Hash of the canonical-ordered final games plus config plus seed. Skips the upsert when unchanged.
   */
  inputsHash?: string | null;
  computedAt?: string | null;
  /**
   * Snapshot of the standings legend shown to families.
   */
  legend?: string | null;
  /**
   * Denormalized parent season status for the public read gate.
   */
  seasonStatus?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Scaffold: disciplinary records. Not yet wired into eligibility.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "sanctions".
 */
export interface Sanction {
  id: number;
  subjectMembership?: (number | null) | TeamMembership;
  game?: (number | null) | Game;
  type?: ('suspension' | 'warning' | 'technical_accumulation' | 'ejection') | null;
  gamesSuspended?: number | null;
  status?: ('active' | 'served' | 'overturned') | null;
  notes?: string | null;
  createdAt: string;
  updatedAt: string;
}
/**
 * Scaffold: per-game availability. Admin-only until member scoping is built.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "availability".
 */
export interface Availability {
  id: number;
  membership: number | TeamMembership;
  game: number | Game;
  response?: ('yes' | 'no' | 'maybe' | 'unknown') | null;
  note?: string | null;
  respondedAt?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Scaffold: per-player box scores. Disabled until a consent model exists.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "player-stats".
 */
export interface PlayerStat {
  id: number;
  game: number | Game;
  team?: (number | null) | Team;
  membership: number | TeamMembership;
  points?: number | null;
  fouls?: number | null;
  rebounds?: number | null;
  assists?: number | null;
  minutes?: number | null;
  enteredBy?: (number | null) | User;
  /**
   * Feature flag. Off until a consent model for sharing individual minor stats exists.
   */
  enabled?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Append-only record of privileged actions. Cannot be edited or deleted.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "audit-log".
 */
export interface AuditLog {
  id: number;
  /**
   * Acting user. Null for system or cron actions.
   */
  actor?: (number | null) | User;
  /**
   * Snapshot of the actor email so the record survives user deletion.
   */
  actorEmail?: string | null;
  /**
   * For example game.finalize, membership.verify, official.assign, import.commit.
   */
  action: string;
  entity: string;
  entityId: string;
  before?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  after?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  reason?: string | null;
  at: string;
  updatedAt: string;
  createdAt: string;
}
/**
 * Game-linked incident reports. Admin-only; youth-safety data.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "game-incidents".
 */
export interface GameIncident {
  id: number;
  game: number | Game;
  filedBy: number | User;
  filedByRole: 'rep' | 'coach' | 'official' | 'admin';
  type: 'injury' | 'conduct' | 'ejection' | 'other';
  involvedTeam?: (number | null) | Team;
  description: string;
  occurredAt?: string | null;
  /**
   * Private, admin-only photo.
   */
  attachment?: (number | null) | IncidentFile;
  status?: ('new' | 'reviewing' | 'closed') | null;
  createdAt: string;
  updatedAt: string;
}
/**
 * Private incident photos. Admin-only download; never public.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "incident-files".
 */
export interface IncidentFile {
  id: number;
  owner: number | User;
  game?: (number | null) | Game;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * System dedupe store for the Idempotency-Key header. Not user editable.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "idempotency-keys".
 */
export interface IdempotencyKey {
  id: number;
  key: string;
  /**
   * For example report:game:123.
   */
  scope: string;
  /**
   * Same key from a different user is rejected 403.
   */
  userId?: string | null;
  /**
   * Hash of the stable logical fields, not the multipart envelope.
   */
  requestHash?: string | null;
  statusCode?: number | null;
  responseBody?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  /**
   * Swept after 24 hours by the TTL cron.
   */
  createdAt: string;
  updatedAt: string;
}
/**
 * System refresh-token store for native sessions. Hashed; not user editable.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "refresh-tokens".
 */
export interface RefreshToken {
  id: number;
  tokenHash: string;
  user: number | User;
  /**
   * Token family id. Reuse detection revokes the whole family.
   */
  family: string;
  expiresAt: string;
  revoked?: boolean | null;
  /**
   * Hash of the token that rotated this one.
   */
  replacedBy?: string | null;
  createdAt: string;
  updatedAt: string;
}
/**
 * System rate-limit hit log. Not user editable.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "rate-limit-hits".
 */
export interface RateLimitHit {
  id: number;
  /**
   * For example report, confirm, import.
   */
  bucket: string;
  /**
   * The actor being limited, for example user id or ip.
   */
  subject: string;
  at: string;
  updatedAt: string;
  createdAt: string;
}
/**
 * Registered passkeys (WebAuthn). Public keys are private.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "webauthn-credentials".
 */
export interface WebauthnCredential {
  id: number;
  user: number | User;
  credentialID: string;
  publicKey: string;
  counter: number;
  /**
   * AuthenticatorTransport[] hint.
   */
  transports?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  deviceType?: ('singleDevice' | 'multiDevice') | null;
  backedUp?: boolean | null;
  /**
   * User-friendly label, e.g. "iPhone".
   */
  name?: string | null;
  lastUsedAt?: string | null;
  createdAt: string;
  updatedAt: string;
}
/**
 * Ephemeral WebAuthn ceremony challenges. Single-use.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "webauthn-challenges".
 */
export interface WebauthnChallenge {
  id: number;
  user?: (number | null) | User;
  value: string;
  type: 'registration' | 'authentication';
  expiresAt: string;
  createdAt: string;
  updatedAt: string;
}
/**
 * Encrypted TOTP secrets. One per user; private.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "mfa-totp".
 */
export interface MfaTotp {
  id: number;
  user: number | User;
  secretEncrypted: string;
  activated?: boolean | null;
  lastStep?: number | null;
  createdAt: string;
  activatedAt?: string | null;
  updatedAt: string;
}
/**
 * Hashed single-use recovery codes. Private.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "recovery-codes".
 */
export interface RecoveryCode {
  id: number;
  user: number | User;
  codes?:
    | {
        hash: string;
        salt: string;
        consumedAt?: string | null;
        id?: string | null;
      }[]
    | null;
  remaining?: number | null;
  generatedAt?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Hashed recovery one-time passcodes. Private.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "email-otp".
 */
export interface EmailOtp {
  id: number;
  user: number | User;
  hash: string;
  purpose: 'recovery' | 'stepup';
  expiresAt: string;
  attempts?: number | null;
  consumedAt?: string | null;
  createdAt: string;
  updatedAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'clubs';
        value: number | Club;
      } | null)
    | ({
        relationTo: 'certification-types';
        value: number | CertificationType;
      } | null)
    | ({
        relationTo: 'certifications';
        value: number | Certification;
      } | null)
    | ({
        relationTo: 'certificate-files';
        value: number | CertificateFile;
      } | null)
    | ({
        relationTo: 'courses';
        value: number | Course;
      } | null)
    | ({
        relationTo: 'pathways';
        value: number | Pathway;
      } | null)
    | ({
        relationTo: 'consent-records';
        value: number | ConsentRecord;
      } | null)
    | ({
        relationTo: 'incident-log';
        value: number | IncidentLog;
      } | null)
    | ({
        relationTo: 'game-reports';
        value: number | GameReport;
      } | null)
    | ({
        relationTo: 'pages';
        value: number | Page;
      } | null)
    | ({
        relationTo: 'announcements';
        value: number | Announcement;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'seasons';
        value: number | Season;
      } | null)
    | ({
        relationTo: 'divisions';
        value: number | Division;
      } | null)
    | ({
        relationTo: 'teams';
        value: number | Team;
      } | null)
    | ({
        relationTo: 'venues';
        value: number | Venue;
      } | null)
    | ({
        relationTo: 'courts';
        value: number | Court;
      } | null)
    | ({
        relationTo: 'team-memberships';
        value: number | TeamMembership;
      } | null)
    | ({
        relationTo: 'games';
        value: number | Game;
      } | null)
    | ({
        relationTo: 'score-reports';
        value: number | ScoreReport;
      } | null)
    | ({
        relationTo: 'scoresheet-files';
        value: number | ScoresheetFile;
      } | null)
    | ({
        relationTo: 'confirmations';
        value: number | Confirmation;
      } | null)
    | ({
        relationTo: 'disputes';
        value: number | Dispute;
      } | null)
    | ({
        relationTo: 'officials';
        value: number | Official;
      } | null)
    | ({
        relationTo: 'game-officials';
        value: number | GameOfficial;
      } | null)
    | ({
        relationTo: 'playoff-brackets';
        value: number | PlayoffBracket;
      } | null)
    | ({
        relationTo: 'bracket-series';
        value: number | BracketSery;
      } | null)
    | ({
        relationTo: 'standings-cache';
        value: number | StandingsCache;
      } | null)
    | ({
        relationTo: 'import-batches';
        value: number | ImportBatch;
      } | null)
    | ({
        relationTo: 'sanctions';
        value: number | Sanction;
      } | null)
    | ({
        relationTo: 'availability';
        value: number | Availability;
      } | null)
    | ({
        relationTo: 'player-stats';
        value: number | PlayerStat;
      } | null)
    | ({
        relationTo: 'audit-log';
        value: number | AuditLog;
      } | null)
    | ({
        relationTo: 'game-incidents';
        value: number | GameIncident;
      } | null)
    | ({
        relationTo: 'incident-files';
        value: number | IncidentFile;
      } | null)
    | ({
        relationTo: 'idempotency-keys';
        value: number | IdempotencyKey;
      } | null)
    | ({
        relationTo: 'refresh-tokens';
        value: number | RefreshToken;
      } | null)
    | ({
        relationTo: 'rate-limit-hits';
        value: number | RateLimitHit;
      } | null)
    | ({
        relationTo: 'webauthn-credentials';
        value: number | WebauthnCredential;
      } | null)
    | ({
        relationTo: 'webauthn-challenges';
        value: number | WebauthnChallenge;
      } | null)
    | ({
        relationTo: 'mfa-totp';
        value: number | MfaTotp;
      } | null)
    | ({
        relationTo: 'recovery-codes';
        value: number | RecoveryCode;
      } | null)
    | ({
        relationTo: 'email-otp';
        value: number | EmailOtp;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  fullName?: T;
  preferredName?: T;
  pronouns?: T;
  phone?: T;
  dateOfBirth?: T;
  isMinor?: T;
  profilePhoto?: T;
  bio?: T;
  club?: T;
  roles?: T;
  status?: T;
  legalHold?: T;
  emergencyContact?:
    | T
    | {
        name?: T;
        relationship?: T;
        phone?: T;
      };
  consents?:
    | T
    | {
        termsVersion?: T;
        privacyVersion?: T;
        guardianConsentVersion?: T;
        acceptedAt?: T;
        acceptedIp?: T;
        marketingOptIn?: T;
        photoOptIn?: T;
      };
  guardian?:
    | T
    | {
        name?: T;
        email?: T;
        phone?: T;
        relationship?: T;
        confirmed?: T;
        confirmationToken?: T;
      };
  notificationPrefs?:
    | T
    | {
        certificationReminders?: T;
        generalUpdates?: T;
        gameReminders?: T;
      };
  mfa?:
    | T
    | {
        enrolled?: T;
        methods?: T;
        enrolledAt?: T;
        required?: T;
        lastVerifiedAt?: T;
      };
  sessionMeta?:
    | T
    | {
        sid?: T;
        aal?: T;
        mfaAt?: T;
        stepUpAt?: T;
        ip?: T;
        userAgent?: T;
        id?: T;
      };
  pushDevices?:
    | T
    | {
        token?: T;
        platform?: T;
        registeredAt?: T;
        lastSeenAt?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "clubs_select".
 */
export interface ClubsSelect<T extends boolean = true> {
  name?: T;
  shortName?: T;
  logo?: T;
  contactEmail?: T;
  contactPhone?: T;
  admins?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "certification-types_select".
 */
export interface CertificationTypesSelect<T extends boolean = true> {
  name?: T;
  category?: T;
  appliesToRoles?: T;
  validityMonths?: T;
  isRequired?: T;
  requiredForRoles?: T;
  renewalUrl?: T;
  relatedCourse?: T;
  description?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "certifications_select".
 */
export interface CertificationsSelect<T extends boolean = true> {
  user?: T;
  type?: T;
  status?: T;
  issueDate?: T;
  expiryDate?: T;
  certificateFile?: T;
  issuingBody?: T;
  credentialId?: T;
  verifiedBy?: T;
  verifiedAt?: T;
  notes?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "certificate-files_select".
 */
export interface CertificateFilesSelect<T extends boolean = true> {
  owner?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "courses_select".
 */
export interface CoursesSelect<T extends boolean = true> {
  title?: T;
  description?: T;
  provider?: T;
  format?: T;
  level?: T;
  cost?: T;
  duration?: T;
  targetAudience?: T;
  registerUrl?: T;
  mandatory?: T;
  requiredForRoles?: T;
  relatedCertificationType?: T;
  externalId?: T;
  modules?:
    | T
    | {
        number?: T;
        title?: T;
        description?: T;
        id?: T;
      };
  tags?:
    | T
    | {
        tag?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pathways_select".
 */
export interface PathwaysSelect<T extends boolean = true> {
  name?: T;
  audience?: T;
  description?: T;
  stages?:
    | T
    | {
        name?: T;
        description?: T;
        order?: T;
        xpReward?: T;
        requiredCertificationTypes?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "consent-records_select".
 */
export interface ConsentRecordsSelect<T extends boolean = true> {
  user?: T;
  kind?: T;
  isMinor?: T;
  termsVersion?: T;
  privacyVersion?: T;
  guardianConsentVersion?: T;
  marketingOptIn?: T;
  photoOptIn?: T;
  acceptedAt?: T;
  acceptedIp?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "incident-log_select".
 */
export interface IncidentLogSelect<T extends boolean = true> {
  title?: T;
  severity?: T;
  status?: T;
  occurredAt?: T;
  discoveredAt?: T;
  realRiskOfSignificantHarm?: T;
  opcNotifiedAt?: T;
  individualsNotifiedAt?: T;
  affectedCount?: T;
  description?: T;
  remediation?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "game-reports_select".
 */
export interface GameReportsSelect<T extends boolean = true> {
  reportType?: T;
  reporterName?: T;
  reporterEmail?: T;
  role?: T;
  gameDate?: T;
  division?: T;
  homeTeam?: T;
  awayTeam?: T;
  location?: T;
  description?: T;
  status?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages_select".
 */
export interface PagesSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  layout?:
    | T
    | {
        hero?: T | HeroBlockSelect<T>;
        richText?: T | RichTextBlockSelect<T>;
        statsGrid?: T | StatsGridBlockSelect<T>;
        faq?: T | FAQBlockSelect<T>;
        cta?: T | CTABlockSelect<T>;
        image?: T | ImageBlockSelect<T>;
        embed?: T | EmbedBlockSelect<T>;
      };
  seo?:
    | T
    | {
        metaTitle?: T;
        metaDescription?: T;
        ogImage?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "HeroBlock_select".
 */
export interface HeroBlockSelect<T extends boolean = true> {
  eyebrow?: T;
  heading?: T;
  subheading?: T;
  ctaLabel?: T;
  ctaHref?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "RichTextBlock_select".
 */
export interface RichTextBlockSelect<T extends boolean = true> {
  content?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "StatsGridBlock_select".
 */
export interface StatsGridBlockSelect<T extends boolean = true> {
  stats?:
    | T
    | {
        value?: T;
        label?: T;
        id?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "FAQBlock_select".
 */
export interface FAQBlockSelect<T extends boolean = true> {
  heading?: T;
  items?:
    | T
    | {
        question?: T;
        answer?: T;
        id?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "CTABlock_select".
 */
export interface CTABlockSelect<T extends boolean = true> {
  heading?: T;
  body?: T;
  buttonLabel?: T;
  buttonHref?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ImageBlock_select".
 */
export interface ImageBlockSelect<T extends boolean = true> {
  image?: T;
  caption?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "EmbedBlock_select".
 */
export interface EmbedBlockSelect<T extends boolean = true> {
  title?: T;
  url?: T;
  height?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "announcements_select".
 */
export interface AnnouncementsSelect<T extends boolean = true> {
  title?: T;
  body?: T;
  tag?: T;
  link?: T;
  pinned?: T;
  publishedAt?: T;
  expiresAt?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  caption?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
  sizes?:
    | T
    | {
        thumbnail?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        card?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        hero?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "seasons_select".
 */
export interface SeasonsSelect<T extends boolean = true> {
  name?: T;
  sport?: T;
  status?: T;
  startDate?: T;
  endDate?: T;
  timezone?: T;
  defaultGameLengthMinutes?: T;
  bufferMinutes?: T;
  seasonSeed?: T;
  standingsConfig?:
    | T
    | {
        pointsWin?: T;
        pointsLoss?: T;
        pointsTie?: T;
        tiebreakers?:
          | T
          | {
              criterion?: T;
              id?: T;
            };
        pointDiffCap?: T;
        mercyEnabled?: T;
        includeForfeits?: T;
        forfeitScoreFor?: T;
        forfeitScoreAgainst?: T;
        forfeitWinPoints?: T;
        forfeitPenaltyPoints?: T;
        pointsForBasis?: T;
        legend?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "divisions_select".
 */
export interface DivisionsSelect<T extends boolean = true> {
  fullPath?: T;
  displayLabel?: T;
  leagueName?: T;
  ageGroup?: T;
  gender?: T;
  tier?: T;
  season?: T;
  scheduleType?: T;
  requiredRampLevel?: T;
  sortOrder?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "teams_select".
 */
export interface TeamsSelect<T extends boolean = true> {
  name?: T;
  club?: T;
  division?: T;
  color?: T;
  logo?: T;
  externalId?: T;
  active?: T;
  importBatch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "venues_select".
 */
export interface VenuesSelect<T extends boolean = true> {
  name?: T;
  address?: T;
  city?: T;
  province?: T;
  postalCode?: T;
  mapsUrl?: T;
  notes?: T;
  blackoutDates?:
    | T
    | {
        date?: T;
        reason?: T;
        id?: T;
      };
  externalId?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "courts_select".
 */
export interface CourtsSelect<T extends boolean = true> {
  name?: T;
  venue?: T;
  active?: T;
  externalId?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "team-memberships_select".
 */
export interface TeamMembershipsSelect<T extends boolean = true> {
  user?: T;
  team?: T;
  role?: T;
  verified?: T;
  verifiedBy?: T;
  verifiedAt?: T;
  invitedEmail?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "games_select".
 */
export interface GamesSelect<T extends boolean = true> {
  season?: T;
  division?: T;
  homeTeam?: T;
  awayTeam?: T;
  venue?: T;
  court?: T;
  startAt?: T;
  endAt?: T;
  status?: T;
  publishState?: T;
  version?: T;
  homeScore?: T;
  awayScore?: T;
  periodScores?:
    | T
    | {
        period?: T;
        home?: T;
        away?: T;
        id?: T;
      };
  forfeit?:
    | T
    | {
        isForfeit?: T;
        outcome?: T;
        forfeitingTeam?: T;
        reason?: T;
      };
  changeLog?:
    | T
    | {
        at?: T;
        actor?: T;
        actorEmail?: T;
        field?: T;
        from?: T;
        to?: T;
        reason?: T;
        id?: T;
      };
  isBye?: T;
  lockedAt?: T;
  externalId?: T;
  notes?: T;
  importBatch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "score-reports_select".
 */
export interface ScoreReportsSelect<T extends boolean = true> {
  game?: T;
  submittedBy?: T;
  submittedForTeam?: T;
  homeScore?: T;
  awayScore?: T;
  periodScores?:
    | T
    | {
        period?: T;
        home?: T;
        away?: T;
        id?: T;
      };
  scoresheetPhoto?: T;
  notes?: T;
  source?: T;
  submittedAt?: T;
  idempotencyKey?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "scoresheet-files_select".
 */
export interface ScoresheetFilesSelect<T extends boolean = true> {
  owner?: T;
  game?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "confirmations_select".
 */
export interface ConfirmationsSelect<T extends boolean = true> {
  game?: T;
  scoreReport?: T;
  confirmingUser?: T;
  confirmingTeam?: T;
  decision?: T;
  photoAcknowledged?: T;
  notes?: T;
  createdAt?: T;
  idempotencyKey?: T;
  updatedAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "disputes_select".
 */
export interface DisputesSelect<T extends boolean = true> {
  game?: T;
  raisedBy?: T;
  reason?: T;
  status?: T;
  assignedAdminEmail?: T;
  resolvedBy?: T;
  resolution?: T;
  createdAt?: T;
  resolvedAt?: T;
  updatedAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "officials_select".
 */
export interface OfficialsSelect<T extends boolean = true> {
  name?: T;
  email?: T;
  phone?: T;
  rampLevel?: T;
  maxGamesPerDay?: T;
  externalId?: T;
  notes?: T;
  linkedUser?: T;
  active?: T;
  importBatch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "game-officials_select".
 */
export interface GameOfficialsSelect<T extends boolean = true> {
  game?: T;
  official?: T;
  officialUserId?: T;
  role?: T;
  assignedBy?: T;
  assignedAt?: T;
  status?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "playoff-brackets_select".
 */
export interface PlayoffBracketsSelect<T extends boolean = true> {
  name?: T;
  division?: T;
  season?: T;
  format?: T;
  status?: T;
  seedSnapshot?: T;
  seededAt?: T;
  publishState?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "bracket-series_select".
 */
export interface BracketSeriesSelect<T extends boolean = true> {
  bracket?: T;
  round?: T;
  slot?: T;
  homeSeed?: T;
  awaySeed?: T;
  homeTeam?: T;
  awayTeam?: T;
  game?: T;
  feedsInto?: T;
  feedsIntoSlot?: T;
  isLosersBracket?: T;
  winner?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "standings-cache_select".
 */
export interface StandingsCacheSelect<T extends boolean = true> {
  division?: T;
  rows?: T;
  inputsHash?: T;
  computedAt?: T;
  legend?: T;
  seasonStatus?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "import-batches_select".
 */
export interface ImportBatchesSelect<T extends boolean = true> {
  kind?: T;
  fileName?: T;
  counts?: T;
  publishMode?: T;
  status?: T;
  createdRecords?: T;
  committedBy?: T;
  committedAt?: T;
  undoneBy?: T;
  undoneAt?: T;
  undoExpiresAt?: T;
  undoWindowMinutes?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "sanctions_select".
 */
export interface SanctionsSelect<T extends boolean = true> {
  subjectMembership?: T;
  game?: T;
  type?: T;
  gamesSuspended?: T;
  status?: T;
  notes?: T;
  createdAt?: T;
  updatedAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "availability_select".
 */
export interface AvailabilitySelect<T extends boolean = true> {
  membership?: T;
  game?: T;
  response?: T;
  note?: T;
  respondedAt?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "player-stats_select".
 */
export interface PlayerStatsSelect<T extends boolean = true> {
  game?: T;
  team?: T;
  membership?: T;
  points?: T;
  fouls?: T;
  rebounds?: T;
  assists?: T;
  minutes?: T;
  enteredBy?: T;
  enabled?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "audit-log_select".
 */
export interface AuditLogSelect<T extends boolean = true> {
  actor?: T;
  actorEmail?: T;
  action?: T;
  entity?: T;
  entityId?: T;
  before?: T;
  after?: T;
  reason?: T;
  at?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "game-incidents_select".
 */
export interface GameIncidentsSelect<T extends boolean = true> {
  game?: T;
  filedBy?: T;
  filedByRole?: T;
  type?: T;
  involvedTeam?: T;
  description?: T;
  occurredAt?: T;
  attachment?: T;
  status?: T;
  createdAt?: T;
  updatedAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "incident-files_select".
 */
export interface IncidentFilesSelect<T extends boolean = true> {
  owner?: T;
  game?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "idempotency-keys_select".
 */
export interface IdempotencyKeysSelect<T extends boolean = true> {
  key?: T;
  scope?: T;
  userId?: T;
  requestHash?: T;
  statusCode?: T;
  responseBody?: T;
  createdAt?: T;
  updatedAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "refresh-tokens_select".
 */
export interface RefreshTokensSelect<T extends boolean = true> {
  tokenHash?: T;
  user?: T;
  family?: T;
  expiresAt?: T;
  revoked?: T;
  replacedBy?: T;
  createdAt?: T;
  updatedAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "rate-limit-hits_select".
 */
export interface RateLimitHitsSelect<T extends boolean = true> {
  bucket?: T;
  subject?: T;
  at?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "webauthn-credentials_select".
 */
export interface WebauthnCredentialsSelect<T extends boolean = true> {
  user?: T;
  credentialID?: T;
  publicKey?: T;
  counter?: T;
  transports?: T;
  deviceType?: T;
  backedUp?: T;
  name?: T;
  lastUsedAt?: T;
  createdAt?: T;
  updatedAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "webauthn-challenges_select".
 */
export interface WebauthnChallengesSelect<T extends boolean = true> {
  user?: T;
  value?: T;
  type?: T;
  expiresAt?: T;
  createdAt?: T;
  updatedAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "mfa-totp_select".
 */
export interface MfaTotpSelect<T extends boolean = true> {
  user?: T;
  secretEncrypted?: T;
  activated?: T;
  lastStep?: T;
  createdAt?: T;
  activatedAt?: T;
  updatedAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "recovery-codes_select".
 */
export interface RecoveryCodesSelect<T extends boolean = true> {
  user?: T;
  codes?:
    | T
    | {
        hash?: T;
        salt?: T;
        consumedAt?: T;
        id?: T;
      };
  remaining?: T;
  generatedAt?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "email-otp_select".
 */
export interface EmailOtpSelect<T extends boolean = true> {
  user?: T;
  hash?: T;
  purpose?: T;
  expiresAt?: T;
  attempts?: T;
  consumedAt?: T;
  createdAt?: T;
  updatedAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "policy-versions".
 */
export interface PolicyVersion {
  id: number;
  /**
   * Current Terms of Use version (e.g. a date or semver).
   */
  termsVersion: string;
  privacyVersion: string;
  /**
   * Current Guardian Consent & Children’s Privacy Notice version.
   */
  guardianConsentVersion: string;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings".
 */
export interface SiteSetting {
  id: number;
  privacyOfficer?: {
    name?: string | null;
    email?: string | null;
    phone?: string | null;
  };
  contact?: {
    email?: string | null;
    phone?: string | null;
  };
  /**
   * Where contested-game and review escalations are sent. Update is super admin only, so a club admin cannot repoint it.
   */
  schedulingAdmin?: {
    /**
     * Recipient for contested-game and review escalations.
     */
    email?: string | null;
    name?: string | null;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "header-nav".
 */
export interface HeaderNav {
  id: number;
  items?:
    | {
        label: string;
        href: string;
        children?:
          | {
              label: string;
              href: string;
              id?: string | null;
            }[]
          | null;
        id?: string | null;
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "footer-nav".
 */
export interface FooterNav {
  id: number;
  sections?:
    | {
        title: string;
        links?:
          | {
              label: string;
              href: string;
              id?: string | null;
            }[]
          | null;
        id?: string | null;
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "policy-versions_select".
 */
export interface PolicyVersionsSelect<T extends boolean = true> {
  termsVersion?: T;
  privacyVersion?: T;
  guardianConsentVersion?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings_select".
 */
export interface SiteSettingsSelect<T extends boolean = true> {
  privacyOfficer?:
    | T
    | {
        name?: T;
        email?: T;
        phone?: T;
      };
  contact?:
    | T
    | {
        email?: T;
        phone?: T;
      };
  schedulingAdmin?:
    | T
    | {
        email?: T;
        name?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "header-nav_select".
 */
export interface HeaderNavSelect<T extends boolean = true> {
  items?:
    | T
    | {
        label?: T;
        href?: T;
        children?:
          | T
          | {
              label?: T;
              href?: T;
              id?: T;
            };
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "footer-nav_select".
 */
export interface FooterNavSelect<T extends boolean = true> {
  sections?:
    | T
    | {
        title?: T;
        links?:
          | T
          | {
              label?: T;
              href?: T;
              id?: T;
            };
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}